### ISSUE TITLE
When using KeePass auto-fill, the dot character is misbehaving.

### ISSUE THREAD

**Issue by springcomp** [springcomp/optimized-azerty-win#73]
The entry contains a regular dot `.` characters but when using auto-fill, this character is misbehaving and appears to be a combining character with the character just before it.

![image](https://user-images.githubusercontent.com/8488398/59852759-cc50a180-936f-11e9-8a10-c11acac5983f.png)

**Comment by springcomp** [comment]
KeePass is using the Win32 `VkKeyScanEx` function to lookup the corresponding key on the keyboard layout. The `.` dot character is U+002e and is defined multiple times in the keyboard layout.

- First defined [here](https://github.com/springcomp/optimized-azerty-win/blob/eeb455bc43a89ad3db75fec2b6e6740449fc6586/KBFRZ71.klc#L51) as a dead-key trigger for the dot above diacritical mark.
- Then [here](https://github.com/springcomp/optimized-azerty-win/blob/eeb455bc43a89ad3db75fec2b6e6740449fc6586/KBFRZ71.klc#L75) at its normal location.
- And a third time [here](https://github.com/springcomp/optimized-azerty-win/blob/eeb455bc43a89ad3db75fec2b6e6740449fc6586/KBFRZ71.klc#L53) for the numeric keypad.

It seems that the first occurrence is found and therefore used instead of the expected normal position.

**Comment by springcomp** [comment]
The only duplicate characters that double as dead-key triggers are the following:

- dot below, replaced by non combining FULL STOP (U+002E)
- inverted breve, replaced by non combining DEGREE SIGN (U+00B0)
- short solidus overlay, replaced by SOLIDUS (U+002F)
- short stroke overlay, replaced by non combining HYPHEN - MINUS (U+002D)
- comma below, replaced by non combining (U+002C)

**Comment by kevin-frugier** [comment]
First of all, thanks @springcomp for this layout which I use with stickers on a traditional AZERTY.
Prior to the AFNOR version, I used a custom AZERTY in which (among other things) I had changed the decimal character from "." to ",".
If I open the KLC on this repository and change just that, the resulting keyboard reintroduces the bug with KeePass and the dots. From the content of the KLC I see that the fix requires some keys to be declared after all the others. And I suppose Microsoft Keyboard Layout Creator re-sorts everything when we open the file manually (confirmed at least when doing a save + compare).
I could try to install all the prerequisites or setup a dev environnement with docker and try to understand how to create the setup without KLC but do you think, since you already ship 2 layouts (Standard + Numérique), that you could add a variant of Standard, for users with a NumPad and set the decimal separator to ","? (Package would contain "Standard", "Numérique" & "Comma")
That would be awesome.

**Comment by springcomp** [comment]
@kevin-frugier Thanks for your feedback.

Yes this is a good idea.

One one hand, I like the idea to have the `,` comma as the decimal separator.
One the other hand, I would not like to deviate from the standard too much to improve the chance for this layout to become the official _de facto_ layout for the NF Z71-300 standard.

However, as shown by #78 you could have created a _pull request_ with your changes and taken advantage of AppVeyor to produce the resulting artifacts. In fact, I have just done that for you.

Please, download the [resulting setup program](https://ci.appveyor.com/project/springcomp/optimized-azerty-win/builds/29082790/artifacts) from AppVeyor and tell me if that is OK for you.

Please, be aware that those artifacts will be automatically deleted in six months as per AppVeyor retention policy.

**Comment by kevin-frugier** [comment]
Thank you very much @springcomp. Tested and approved. I understand why you don’t want to deviate too much from the standard and I didn’t know this repo was so automated that I could have done it myself. Thx again

**Comment by springcomp** [comment]
@kevin-frugier, following changes #80, I updated this PR to produce a new compatible release.
You can find the built artifacts from the CI server.

**Comment by springcomp** [comment]
@kevin-frugier, following changes #82, I updated this PR to produce a new compatible release.
You can download the [build artifacts](https://ci.appveyor.com/project/springcomp/optimized-azerty-win/builds/29224170/artifacts) from the CI server.

**Comment by springcomp** [comment]
@kevin-frugier, following changes #85, I updated this PR to produce a new compatible release.
You can download the [build artifacts](https://ci.appveyor.com/project/springcomp/optimized-azerty-win/builds/29225463/artifacts) from the CI server.

**Comment by Pierrounator** [comment]
This is the worst change you could do and only for 1 person asking for it…
Physical keyboards you can buy have the DOT on that key and now we can't use it as it should be used. I bought mine on LDLC and I didn't print my own stickers.

You need to type a date? Forget that key.
You need to type a phone number? Forget that key.

Excel, calculator, … are used to the dot. This is really useless to me. This change is clearly for someone using numbers in a way they shouldn't use it.

I tried to download an old release but I still get the coma. I'll try to find another NF Z71-300 with default layout.

**Comment by kevin-frugier** [comment]
@Pierrounator What's will all the rage and down votes all over the place?!

Which variant are you using?
With current driver (KBFRZ71_amd64 on its own) I have the following behavior on a French system with a "." printed, like you, on my physical numpad decimal separator key:

**Français - AZERTY NF Z71-300**
- Notepad: "." is produced
- Excel with standard FR regional settings "," is produced
- Excel with US regional settings "." is produced

**Français - AZERTY NF Z71-300 (Numérique)**
(supposed to be used only for non-physical num pads if we follow the documentation)
- Notepad: "," is produced
- Excel with standard FR regional settings "," is produced
- Excel with US regional settings "." is produced

For some odd reason the "Français - AZERTY NF Z71-300" classic variant no longer produces the "," on its own but that should be what **you** expect anyway so why are you unhappy?

As for the initial choice of the comma as decimal separator for applications not "regional settings aware", we can re-discuss that with @springcomp if needed. The goal of AZERTY NF Z71-300 is to be able to type in "french" without counting on softwares to replace mistakes (like it was the case for "œ" and others in the past). The virtual key code for the key is (VK_)DECIMAL so it's meant to be used to type a decimal separator. We got used to something else because standard layouts/keyboard manufacturers were racists :D A good showcase for me is "Are you able to type a french text with french numbers (amounts) in raw notepad?".

(as per your examples, IP adresses indeed use dots, regular and standardized date and phone numbers formats don't)
 
If you follow the thread back to my initial request, you would see I only requested for a custom variant. So when we understand the status of the current version (with the mismatch between the 2 variants) we can then potentially move the comma stuff to an explicit variant hence giving more choice to the user.

**Comment by Pierrounator** [comment]
Well I was upset yes because I use NF Z71-300 everyday at home and at work and when I got a new computer at work I couldn't type phone numbers (because we put dots to make it readable), IPs and numbers anymore with that key. I work in an hospital for TV, WiFi, Phone, … and I use that dot key like 200 times a day.

I installed the NF Z71-300 tuesday on W11 with your PowerShell command and then on Notepad, … it was producing the coma and not the dot.
I uninstalled it and downloaded the previous version (1.8) and it was still producing the coma. But today I saw it was producing the dot (thank god). I thought you forced an update or something like that.
I've never seen the Numérique option… So I'm not sure what you're talking about.

I'm still convinced this key should stay as a dot. Yes, in France we are told to use the coma for the numbers. But if you do some programmation, … the coma will produce an error. If you really need to put a coma to make it pretty, you still have the coma key under the letters.
For example, in javascript doing `let = 1,34;` is wrong.
For the phone numbers, I know we shouldn't use the dots but to save customers phone numbers it's easier to read `01.23.45.67.89` instead of `0123456789`.
And as I said, the manufactured Azerty+ keyboard has a dot printed on this key. (https://www.ldlc.com/fiche/PB00544268.html)

_Btw thank you for that keyboard layout. I use it since many years and I was happy to find the perfect mix between AZERTY and BÉPO. I was about to switch to BÉPO but I knew I wouldn't be able to use it at work since it's too much different. At least, they let me use this AZERTY+ and my coworkers are not fully lost if they have to use my keyboard_

**Comment by Rehvaro** [comment]
Just to be sure.
There is no configuration or any other ways to get back the dot on the numpad since this commit ? Because it's very unconvenient to have a comma here :S 
Thank you anyway for this layout I now use everywhere :)

**Comment by springcomp** [comment]
@Rehvaro, #78 showed that you could submit a PR and produce a build for your own consumption.

In fact, I [did just that](#142) for you.
Please, [download the resulting artifacts](https://ci.appveyor.com/project/springcomp/optimized-azerty-win/builds/51130127/artifacts) and enjoy your own, very private, version of the layout 😉.

**Comment by Rehvaro** [comment]
Oh Thank you !
Sorry, I only know the basics of GIT, and don't use github very often.
I suppose this PR and the corresponding artifacts will not updates with futur commits of the main branch, so in case I want to update I will just have to make a PR like this to have the newer version but just with this tiny difference ? Or am I wrong ? ^^

Thank you

**Comment by springcomp** [comment]
@Rehvaro  that’s exactly right !
