### ISSUE TITLE
Wrong unicodes for inequality symbols

### ISSUE THREAD

**Issue by 240-185** [springcomp/optimized-azerty-win#79]
The driver outputs ⩽ (U+2A7D) and ⩾ (U+2A7E) for inequality symbols.

Should be ≤ (U+2264) and ≥ (U+2265), implemented in many fonts, whereas the two former glyphs are less supported.

For example U+2264 and U+2265 are supported by Calibri, not U+2A7D and U+2A7E (Word switches automatically to Cambria Math, but only because it can).

**Comment by springcomp** [comment]
Hi, thank you for your feedback and for using the layout.

I must admit I was very surprised to observe that those two characters were as the ones I included. Since this is a hobby and open source project, I cannot afford to buy the official standard document. However, I based my work on [a working draft](https://github.com/springcomp/optimized-azerty-win/wiki/Working-Draft) that floated around on the Internet in the later stages of the standard.

I think this document is fairly accurate but I would be happy to have a more reliable source to confirm or correct this layout.

**Comment by springcomp** [comment]
I was briefly in contact with @cyril-L who had access to the final document in a local subsidiary of AFNOR. Maybe he remembers something about those characters?

**Comment by cyril-L** [comment]
Yes, the final version of the standard used U+2264 and U+2265, not the slanted versions like in the draft. Those are the [notes](https://github.com/cyril-L/normalized-azerty/blob/master/kbdrefs/nf_z71_300.md) I took while reading the official document.

**Comment by springcomp** [comment]
Awesome @cyril-L , thank you!
I'll go ahead a publish an official version, then.
